version: "3"

services:
  api:
    image: thiagosf85/mynode:dev
    build:
      context: ./node/api
      dockerfile: Dockerfile
    container_name: api
    networks:
      - node-network
    volumes:
      - ../node/api:/usr/src/app/api
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    # command: node index.js

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=node
    networks:
      - node-network

  nginx:
    image: nginx:latest
    container_name: nginx
    tty: true
    restart: always
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
